from typing import Protocol, List
from app.domain.chat import Conversation, Message

class ConversationRepository(Protocol):
    async def create(self, project_id: str) -> Conversation: ...
    async def get_by_id(self, conversation_id: str) -> Conversation | None: ...
    async def list_by_project(self, project_id: str) -> List[Conversation]: ...
    async def delete(self, conversation_id: str) -> bool: ...

class MessageRepository(Protocol):
    async def create(self, conversation_id: str, role: str, content: str) -> Message: ...
    async def get_by_id(self, message_id: str) -> Message | None: ...
    async def list_by_conversation(self, conversation_id: str) -> List[Message]: ...
    async def delete(self, message_id: str) -> bool: ...
