from typing import Protocol
from app.domain.user import User


class UserRepository(Protocol):
    async def get_by_email(self, email: str) -> User | None: ...
    async def create(self, email: str, password_hash: str) -> User: ...
from typing import Protocol
from app.domain.user import User

class UserRepository(Protocol):
    async def get_by_email(self, email: str) -> User | None: ...
    async def create(self, email: str, password_hash: str) -> User: ...
