from typing import Protocol, List
from app.domain.project import Project, Prompt

class ProjectRepository(Protocol):
    async def create(self, user_id: str, name: str, description: str | None) -> Project: ...
    async def get_by_id(self, project_id: str, user_id: str) -> Project | None: ...
    async def list_by_user(self, user_id: str) -> List[Project]: ...
    async def update(self, project_id: str, user_id: str, name: str, description: str | None) -> Project | None: ...
    async def delete(self, project_id: str, user_id: str) -> bool: ...

class PromptRepository(Protocol):
    async def create(self, project_id: str, name: str, content: str) -> Prompt: ...
    async def get_by_id(self, prompt_id: str) -> Prompt | None: ...
    async def list_by_project(self, project_id: str) -> List[Prompt]: ...
    async def update(self, prompt_id: str, name: str, content: str) -> Prompt | None: ...
    async def delete(self, prompt_id: str) -> bool: ...
