from typing import Protocol, List, Optional
from app.domain.prompt import Prompt


class PromptRepository(Protocol):
	async def create(self, project_id: str, prompt_text: str) -> Prompt: ...
	async def list_by_project(self, project_id: str) -> List[Prompt]: ...
	async def get_by_id(self, prompt_id: str) -> Optional[Prompt]: ...
